server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.112.101
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    #数据库索引
    database: 0
    host: 192.168.112.101
    port: 6379
    password:
  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    username: user04
    password: 1234
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
ly:
  sms:
    accessKeyId: LTAIsWzGHfExHdcV
    accessKeySecret: xKPhTCRj3Nlbyl1dPy3rmbaKqGVouh
    signName: ly商城
    verifyCodeTemplate: SMS_164150583